#!/bin/bash
#自動備份，設置crontab之後，每四小時備份一次，並使用網上下載的脚步自動上傳文件夾到谷歌drive
#使用方法：設置好下面的目錄，文件名，上傳文件夾ID，密碼等即可。這個是自動運行的。
set -e
echo "backup and call upload, $0"
sleep 1 &&
timestamp=$(date +%Y_%m_%d_%H%M)
path=/your/backup_path
path1=/your/backup_path/blog
path2=/your/backup_path/main_site
uploadsh=/your/path/upload.sh
fid=your_root_folderID_on_Google_drive
	db1=blog_data_$timestamp.sql.gz
	db2=ghost_data_$timestamp.sql.gz
	ct1=blog_content_$timestamp.tar.gz
	ct2=ghost_content_$timestamp.tar.gz

dbusr1=database_usr1
dbpwd1=database_password1
dbname1=database_name1

dbusr2=database_name2
dbpwd2=database_password2
dbname2=database_name2

#不知道打了括號，會不會按序執行
#dump and zip databases#########################################################
(
echo "dumping db1: $path1$db1..."

mysqldump --user=$dbusr1 --password=$dbpwd1 --databases $dbname1 --single-transaction | gzip > $path1/$db1

echo "db1 backed up."

echo "dumping db2: $path2$db2..."

mysqldump --user=$dbusr2 --password=$dbpwd2 --databases $dbname2 --single-transaction | gzip > $path2/$db2

echo "db2 backing up done."

#backup content folder under ghost root########################################

echo "compressing ct1..."

tar -czf $path1/$ct1 /path/to/blog/content

echo "done."

echo "compressing ct2..."

tar -czf $path2/$ct2 /path/to/ghost/content

echo "done."

##############################################################################
echo "To: 小X recipient@gmail.com" > /your/path/email.txt
echo "From: 服務器 yourgmail@gmail.com" >> /your/path/email.txt
echo "Subject: 數據備份通知：$(date +%Y年%m月%d日%H時%M分)" >> /your/path/email.txt
echo "Mime-Version: 1.0" >> /your/path/email.txt
echo "Content-Type: text/html" >> /your/path/email.txt
echo  >> /your/path/email.txt
echo "<html>" >> /your/path/email.txt
echo "<body>" >> /your/path/email.txt
echo "<h1>以下備份文件已成功上傳至Google Drive，請檢查有無異常情況：</h1>" >> /your/path/email.txt
echo "" >> /your/path/email.txt
##############################################################################

echo "uploading all backup folder to Google Drive..."

$uploadsh -r $fid $path1
sleep 1 &&
#/your/path/upload.sh -r your_root_folderID_on_Google_drive /your/backup_path/blog
echo "$uploadsh -r $fid $path1"
echo "Done."
$uploadsh -r $fid $path2
sleep 1 &&
#complete#############################################################################
echo "</body>" >> /your/path/email.txt
echo "</html>" >> /your/path/email.txt

sleep 1 &&

#send email or not ####################################################################################
#sendemail.txt is generated by upload.sh,  and email.txt is generated by both semishell.sh and upload.sh
SEND_EMAIL=0
SEND_EMAIL=$(cat "/your/path/sendemail.txt")

if [ $SEND_EMAIL -eq 1 ]
then
msmtp recipient@gmail.com < /your/path/email.txt
fi

sleep 1 &&
#delete local backup files #############################################################################
rm -rf $path1/*
rm -rf $path2/*
)
echo "all local backup files have been removed."
